### ISSUE TITLE
Filter large amount of players by Grand Company.

### ISSUE THREAD

**Issue by AdriaanDeVos** [XIVStats/XIVStats#11]
Let me begin first by saying that it is always hard to find the active player count when you try to deduce it from other information. In my opinion, the current line for deciding if a player is active/not active is too high. There are tons and tons of players who are really active working through the MSQ and keep playing after they choose their Grand Company.

You can see this if you look at "GRAND COMPANY DISTRIBUTION - ALL PLAYERS". By far, most of the accounts do not have a Grand Company and are either bots, or people quitting the game after a few days. Every player that plays for more than a week a bit actively would have gotten a Grand Company.

I propose to remove all the "No Grand Company" players/data from the player statistics to get a better overview of the playerbase by disregarding bots and people that have barely tried the game out.

This would cause all the ALL PLAYERS/ACTIVE PLAYERS graphs to become more meaningful and more correct.

**Comment by Bwin4L** [comment]
That would filter all low level players (<level 20 IIRC) that are actually playing the game and aren't bots.

I agree it's hard to filter bots, maybe we should then filter players that are level 1 on only one class and didn't level up since last census instead? That prunes 2,682,034 characters from the March census.
We could also add all level 20+ players that don't have any mounts and minions to the shit list (an additional 308,800 players removed).

By the way, I'm all for e.g. removing them in the site views and graphs if that is the dev's wishes, but not for completely removing them from the DB as I think interesting data would get filtered out.

**Comment by Pricetx** [comment]
Determining activity from the available information is tricky. At present, the check is based on ownership of the Yol mount from 4.0, which is obviously becoming less relevant as this patch becomes older.

An ideal system in the future will involve tracking changes between censuses. 

For now, this will be closed. However, suggestions are welcome over at XIVStats-Gatherer-Java.
