### ISSUE TITLE
The zipped May 2017 DB offered for download is only 1.2 MB

### ISSUE THREAD

**Issue by Bwin4L** [XIVStats/XIVStats#13]
Could there have been a problem during its generation?

**Comment by ReidWeb** [comment]
Confirmed, looks to be an issue. @Pricetx will need to investigate

**Comment by Pricetx** [comment]
I can indeed see that the file is only around 1MB, which definitely doesn't match the census run which appears to be complete.

The automatically generated email report for the May run has not arrived in my inbox. I don't currently know the reason for this as the script executed from cron and must have successfully finished otherwise the new page wouldn't have gone line (that's the last line of the script). I have checked the postfix mail queue, but it's empty and all other mail is working.

As we are now past the 1st of the next month the June census is already underway. As a result of this, the database has been cleaned for the new census that is currently being built.

As a precaution, I have disabled the remaining script execution for the June census. That means that the census itself will continue to run, but once it completes it will not automatically generate the page or dump the database. This will allow me to step through it manually and see if there is an issue somewhere.

Additionally on the back of this, I could add some sanity checking for the size of the dumped database. Now that I have a few historical successful runs I can see the database should be at least 800MB. In a normal month where the census starts on the 1st of the month, this would give me 2-3 weeks to correct any database dumping issues before the next month commences. Unfortunately, due to hardware issues it kicked off quite late last month so there was very limited opportunity to spot a fault before the next month kicked in.

If you have any further suggestions around this, please let me know. Regarding this month's data, I have daily MySQL backups, so I will be able to restore the required data, but it may take me a day or two to get around to it.

**Comment by Pricetx** [comment]
The backup restoration process went smoothly, so there wasn't much work required on my part. The DB is now available on the site, but I will provide a direct link here for your convenience:

https://ffxivcensus.com/2017-05/ffxivcensus-2017-05.zip

I am leaving this issue open until I implement some of the remediation steps.

**Comment by Bwin4L** [comment]
Thank you!

**Comment by ReidWeb** [comment]
@Pricetx status? can this be closed
