### ISSUE TITLE
No updates for Stormblood? 

### ISSUE THREAD

**Issue by fahy** [XIVStats/XIVStats#19]
Hi there.

Just wondering why there hasn't been an update for Stormblood. It has been a couple of months since release.

Also, the page for the existing data seems to be missing (I'm just getting a white page when I go to the site https://ffxivcensus.com/ )

An update would be much appreciated! :)

**Comment by ReidWeb** [comment]
Hello @fahy ,

Unfortunately I haven't been able to update the census gatherer due to IRL obligations that are preventing me from doing any work on this for the time being.

Much that I would love to get it done, it is likely not something I will personally be able to update the gatherer for until later this year or perhaps early next year - to be honest I have absolutely no idea when.

Unfortunately at this current time the job parsing code requires two major updates that would need to be applied before any new data can be gathered and run:

- update the gatherer to allow for the new positioning of jobs on the web page

- update the gatherer to allow for the new jobs

Furthermore new database fields would be required for the new jobs, and the web side of things would need to be updated by either myself or @Pricetx .

This is why you will not see any new censuses for the time being - at least until myself or someone else updates the gatherer.

Any Java developers, or any one with programming experience in general - feel free to take it upon yourself to update the gatherer, it would be really appreciated by myself and the community of FFXIV. I can support you in understanding the code that makes up the gatherer if needs be.

**Comment by matthewhillier** [comment]
I've raised a Pull Request against the XIVStats-Gatherer-Java repo to add Stormblood support. There's a slight issue with tracking completion of the MSQ for 4.0, otherwise seems fairly straight forward! :)

**Comment by ReidWeb** [comment]
Woops, shouldn't close this until PHP side is updated

**Comment by Pricetx** [comment]
PHP side has been updated. Did a test run of 1 million IDs, and everything looks good.
