### ISSUE TITLE
Report progress with php (into a file, or into the output HTML)

### ISSUE THREAD

**Issue by Balls0fSteel** [XIVStats/XIVStats#22]
So as the current script can take quite long, and even with the new pull request... it would be great to see a progress report. Maybe percentage, or just simple steps.

(A simple $variable_sql that we increment each query and a simple $variable_logic that we implement after prints and whatnot. And of course, we write out the current progress into a file, or into the HTML file somehow.)

**Comment by Pricetx** [comment]
You would have to be careful how such a thing were implemented. As it is, the current automation pipes the output from the PHP script to a HTML file. If the script output progress to STDOUT in the same way, this would end up being embedded at the top of the web page.

A simple solution would just be doing something like having the script itself output to a file rather than STDOUT, which frees up STDOUT to do useful stuff.

**Comment by matthewhillier** [comment]
Agreed. In the new branch, there's only 2 queries and it's fetching those that takes the time, not iterating through rows, so it would really need to be a wrapper around the PHP generation, not within it itself.

**Comment by Balls0fSteel** [comment]
Whoops, you are right. Guess this ticket can be closed.

**Comment by Balls0fSteel** [comment]
(I mean the new generation is so fast, there is just no need for this.
