### ISSUE TITLE
Give job distribution based on achievements

### ISSUE THREAD

**Issue by Ellante** [XIVStats/XIVStats#4]
Hey !

Just discovered your site with some friends we think it's pretty cool :D

We were just wondering why there were only datas about class distribution and no data at all about job distribution? Our guess is that you parse the data from the Lodestone and count all the players having a class at 60.

I have no idea how you guys are parsing and if there are limitations of some sort, but have you thought of counting job distribution based on the level 50 and 60 job quests achievements?

Keep up the good work! Cheers \o

**Comment by ReidWeb** [comment]
Hi @Ellante,

Thank you!

This is an interesting idea, we could gather achievement data - but we have not opted to due to:

- The sheer amount of data that would involve, we'd have to either catalog every achievement in the game and add it as a field in our database or we'd have to store the raw data for every character.

- Not every character has their achievements public - so the data would be somewhat skewed based upon that.

This is the reason we just use class levels as opposed to those for jobs. Also the number of characters with a class at 60 but not having the job at 60 would be rather low?

@Pricetx I'd be interested in your input on this one.

I hope I've given you the answer you were looking for? Get back to us if you have any further questions.

**Comment by Pricetx** [comment]
Hi,

It was originally my decision that we didn't track achievements, and at the time it was purely for the reason that achievements are not public by default. This means that even if I did track them, the numbers would be far lower than they should be as most players won't be tracked. In this instance I'd rather the data be missing altogether than blatantly wrong.

Thanks for the suggestions though, they're often helpful for gathering data I hadn't previously considered.

**Comment by Pricetx** [comment]
Unfortunately, Square has not provided a way to reliably track achievements so this remains impossible. Thank you for the suggestion though.
